//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaSorter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultimediaSorter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d - День месяца, в диапазоне от 1 до 31.
        ///dd - День месяца, в диапазоне от 01 до 31.
        ///M - Месяц, в диапазоне от 1 до 12.
        ///MM - Месяц, в диапазоне от 01 до 12.
        ///MMM - Сокращенное название месяца.
        ///MMMM - Полное название месяца.
        ///y - Год, в диапазоне от 0 до 99.
        ///yy - Год, в диапазоне от 00 до 99.
        ///yyy - Год в виде как минимум трех цифр.
        ///yyyy - Год в виде четырехзначного числа.
        ///&apos;строка&apos; - Буквенный разделитель строк..
        /// </summary>
        internal static string DirMaskToolTip {
            get {
                return ResourceManager.GetString("DirMaskToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некорректная маска.
        /// </summary>
        internal static string NotCorrectMask {
            get {
                return ResourceManager.GetString("NotCorrectMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор папки с фотографиями.
        /// </summary>
        internal static string SelectFilePath {
            get {
                return ResourceManager.GetString("SelectFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор папки для сохранения фотографий.
        /// </summary>
        internal static string SelectSaveFilePath {
            get {
                return ResourceManager.GetString("SelectSaveFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сортировка завершена..
        /// </summary>
        internal static string SortComplite {
            get {
                return ResourceManager.GetString("SortComplite", resourceCulture);
            }
        }
    }
}
